-- create

CREATE TABLE TEST(
    ID INT,
    NAME VARCHAR(10),
    PASSWORD VARCHAR(20))

-- retrieve

SELECT KHH,SFQYDKDF FROM 
	(SELECT KHH,SUM(DECODE(DFDKQY,'否',0,1)) AS SFQYDKDF FROM R_TT_HQCXZHMXB GROUP BY KHH) 
	WHERE SFQYDKDF>0
-- update
-- delete